### ISSUE TITLE
Error when importing PowerShell SQL Server module version 22.1.1 to Azure Automation

### ISSUE THREAD

**Issue by jgador** [microsoft/SQLServerPSModule#54] opened 2023-07-16 04:57 UTC
When attempting to import the PowerShell SQL Server module version 22.1.1 with runtime version 5.1 into Azure Automation, the following error is encountered:

Invoke-Sqlcmd : Method not found: 'Void Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.SqlColumnEncrypti onAzureKeyVaultProvider..ctor(Azure.Core.TokenCredential)'. At line:26 char:1 + Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $SqlCommand ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidResult: (:) [Invoke-Sqlcmd], MissingMethodException +
FullyQualifiedErrorId : ExecutionFailed,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

I had no problem when using the version 21.1.18256

**Comment by Matteo-T** [comment] 2024-01-16 07:52
Looks like a duplicate of #65

**Closed as completed by Matteo-T** 2024-01-16 07:52 UTC
Labels: duplicate
